### ISSUE TITLE
ScoreHud Addon

### ISSUE THREAD

**Issue by JackMD** [RedCraftGH/RedSkyBlock#12]
Hey so alot of people have been asking me to add support for your plugin to ScoreHud. The thing is that I am unfamiliar with your API and what your plugin provides. So its requested that you make an addon that would be supported by ScoreHud for your plugin. 

Details on how to make the addon are here
https://github.com/JackMD/ScoreHud/wiki

**Comment by JackMD** [comment]
You can either maintain the addon you make over here on your repo or make a pr and add it here
https://github.com/JackMD/ScoreHud/tree/addons

**Comment by RedCraftGH** [comment]
Alright, I'll see what I can do :)

**Comment by AlexPads** [comment]
Yayayayayaya

**Comment by RedCraftGH** [comment]
I have made the addon, and so I am closing this issue. However, the addon won't be usable until I release a new update for RedSkyBlock (hopefully soon).

**Comment by JackMD** [comment]
Also when you do release it please (im not forcing you to do so but) consider releasing the addon here via making a PR. Doing so would let people know that the addon exists and so they could stop spamming me and hopefully you as well for the addon.

https://github.com/JackMD/ScoreHud-Addons
