### ISSUE TITLE
Suggestion :p

### ISSUE THREAD

**Issue by LeoBdt** [RedCraftGH/RedSkyBlock#13]
Hello, it'd be cool if you add an island size system.

For example : 

The size of an island is limited to 100*100 and if the player want to increase it he'll have to place valuable blocks like diamond block. 

/is size will return : 

Your island is limited to 100*100
You need X point of value to increase the limit.

**Comment by RedCraftGH** [comment]
Hello! Thank you for the suggestion. However, I think that this feature would be more server specific and not useful to all users of this plugin; for this reason, I will not be adding the feature you request.

Luckily, in the next release of RedSkyBlock, a new RedSkyBlock API will be available which can be used to create add-ons for the plugin very easily. Using the built-in /is increase and /is decrease commands along with the RedSkyBlock getSize(Player $player) function, it should be possible for you, or another developer, to create the feature(s) that you'd like in an add-on.

The next release of RedSkyBlock is estimated to be released Friday, April 26, 2019.
