### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by LeoBdt** [RedCraftGH/RedSkyBlock#14]
Error: Undefined variable: player
File: plugins/RedSkyBlock_dev-79.phar/src/RedCraftPE/RedSkyBlock/EventListener
Line: 456
Type: ErrorException

~~THIS CRASH WAS CAUSED BY A PLUGIN~~
BAD PLUGIN: RedSkyBlock v3.1.0

Code:

Backtrace:
#0 plugins/RedSkyBlock_dev-79.phar/src/RedCraftPE/RedSkyBlock/EventListener(456): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined variable: player, string phar:///home/leo/skyblock/plugins/RedSkyBlock_dev-79.phar/src/RedCraftPE/RedSkyBlock/EventListener.php, integer 456, array Array())
#1 src/pocketmine/plugin/MethodEventExecutor(38): RedCraftPE\RedSkyBlock\EventListener->onPickup(pocketmine\event\inventory\InventoryPickupItemEvent object)
#2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(RedCraftPE\RedSkyBlock\EventListener object, pocketmine\event\inventory\InventoryPickupItemEvent object)
#3 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\inventory\InventoryPickupItemEvent object)
#4 src/pocketmine/entity/object/ItemEntity(218): pocketmine\event\Event->call()
#5 src/pocketmine/Player(1568): pocketmine\entity\object\ItemEntity->onCollideWithPlayer(pocketmine\Player object)
#6 src/pocketmine/Player(1766): pocketmine\Player->checkNearEntities()
#7 src/pocketmine/level/Level(849): pocketmine\Player->onUpdate(integer 8759)
#8 src/pocketmine/level/Level(794): pocketmine\level\Level->actuallyDoTick(integer 8759)
#9 src/pocketmine/Server(2435): pocketmine\level\Level->doTick(integer 8759)
#10 src/pocketmine/Server(2566): pocketmine\Server->checkTickUpdates(integer 8759, double 1556376592.2112)
#11 src/pocketmine/Server(2335): pocketmine\Server->tick()
#12 src/pocketmine/Server(2196): pocketmine\Server->tickProcessor()
#13 src/pocketmine/Server(1775): pocketmine\Server->start()
#14 src/pocketmine/PocketMine(258): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/leo/skyblock/, string /home/leo/skyblock/plugins/)
#15 (1): require(string phar:///home/leo/skyblock/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by RedCraftGH** [comment]
Hello! Thank you for reporting this bug! The bug has been fixed in RedSkyBlock 3.1.1 which you can download at Poggit!
