### ISSUE TITLE
[Suggestion] Permission for Void

### ISSUE THREAD

**Issue by AlexPads** [RedCraftGH/RedSkyBlock#16]
Could there be a permission for the Void so that if Players that have say like skyblock.voidsave
could get teleported back to their island unharmed but normal players would die and loose all their stuff like when you have void off?

**Comment by AlexPads** [comment]
@RedCraftGH Pull request Was Submitted but its pretty simple to do yourself :) if you don't like my Garbage GitHub editor Formatting rn because I'm not home LOL

**Comment by RedCraftGH** [comment]
Thanks for the suggestion @AlexPads! I really like it! I am definitely going to be implementing this as soon as I can.

**Comment by AlexPads** [comment]
Thanks @RedCraftGH
