### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by isoz** [RedCraftGH/RedSkyBlock#19]
- When someone does the /is reset command, does it just send them to a new island but doesn't physically remove their old island from the world?

- Why does it keep count of how many islands the player had when doing /is reset?

If it doesn't delete the player island I assume that in a server with a decent number of players the world file will eventually become way too big.

Also while I'm at it ill suggest something, possibly add an expiry option? If the player doesn't login for say, 60 days, the island gets removed.

**Comment by RedCraftGH** [comment]
> When someone does the /is reset command, does it just send them to a new island but doesn't physically remove their old island from the world?

When someone does /is reset it does just move them to a new island, this was a quick and dirty workaround for a problem I was facing at the time; I am, however, currently working on making a much better island reset.

> Why does it keep count of how many islands the player had when doing /is reset?

It shouldn't be keeping count of the number of islands a player has had when doing /is reset.

> If it doesn't delete the player island I assume that in a server with a decent number of players the world file will eventually become way too big.

Yea, a lot of problems start occurring after the number of islands gets to be too high. Luckily I knew about this and am working on getting rid of this problem.

> Also while I'm at it ill suggest something, possibly add an expiry option? If the player doesn't login for say, 60 days, the island gets removed.

I think that is a really good idea! I'll see what I can do :)

**Comment by isoz** [comment]
It is keeping count, I did 8 /is reset and in my skyblock.yml its showing Islands: 8

Thank you

**Comment by RedCraftGH** [comment]
That is a counter of all islands that are ever generated by the plugin. If a player resets their island then the plugin must generate a new island which increases the counter by 1.

> Also, I don't know, just something that came to my mind, wouldn't simply setting the Area XYZ to 0 (air) do the job?

It's not quite that simple. The area of each island can vary hugely from island to island; an island can be as big or little as the user of the plugin wishes to make it, this means that setting the area to air would be incredibly inefficient and could cause monstrous amounts of lag for the server.

**Comment by isoz** [comment]
Hey, I was checking the events and I noticed that in the move event you're not checking if the players has left the island or is on the edge of it's island, so technically they can fly to each others islands?

If that's the case what's the point of "locking" the island if there's nothing checking the players entering or leaving islands?

I want to use this in production but this little annoyances are killing me :D

**Comment by RedCraftGH** [comment]
> Hey, I was checking the events and I noticed that in the move event you're not checking if the players have left the island or are on the edge of it's island, so technically they can fly to each others islands?

Yea, it is possible to fly to another player's island; I did it that way previously because the old island generation algorithm--the same one used in the current release (changed in the next release)--generates islands diagonally from each other in one direction. This meant there would be a low chance of flying to another player's island given a player even had the permission to fly. Basically, the system was developed on speculation that it __probably__ wouldn't happen. Of course, in the next release this is all changed as most of the island generating is going to be different.

**Comment by isoz** [comment]
![image](https://user-images.githubusercontent.com/6126350/58754091-78b20d00-84c1-11e9-9aba-380d97fe662d.png)

Starting to show problems with 30 players online

![image](https://user-images.githubusercontent.com/6126350/58754098-88c9ec80-84c1-11e9-8caa-6654351e0439.png)

**Comment by RedCraftGH** [comment]
@isoz I think I am going to push the next SB update tonight; I felt inspired so I've been working on it non-stop :P.

This should help with your problems, but, unfortunately, I was not so smart when I was creating the yaml files and so I didn't add a version number, which means it's impossible for me to detect which version of files is being used for the SB plugins and update them. This means that the next update is not going to be backward compatible, but all future updates after will be 100% backward compatible.

**Comment by isoz** [comment]
@RedCraftGH That's awesome man, thank you for working on it, really appreciated, make a donation link in the page of the plugin and I'll contribute to your time, this can easily be the best skyblock plugin in PM with some adjustments. What sold me was mostly the Island Settings which seems so easy to implement yet all the others fail to do it.

It's OK man, if I have to reset and the stability gets better then there's no problem, I'm sure my players will understand and I'll reward them one way or another.

I'm curious if you're going to keep the database in yaml? You know YML should not be used as a database, I would rather see sqlite, mysql or even json in the future.

Thanks!

**Comment by RedCraftGH** [comment]
Thanks for the compliments, they really mean a lot :)

I am hoping to change the database from YML soon; I am relatively familiar with JSON, so that will be the most likely option for me in the future.

**Comment by isoz** [comment]
I mean I'm not a developer and I can work well with SQL, shouldn't be too complicated if you give a few minutes of your time. Plus there's things like this https://github.com/poggit/libasynql but JSON already sounds way better than yaml for storing data.

No response about the donation link? you're not interested?

**Comment by RedCraftGH** [comment]
I've never really worked with SQL, but I will give it a go and see what happens.

I will put a donation link up in the readme.
