### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AlexPads** [RedCraftGH/RedSkyBlock#2]
Hello, I am  a Developer Myself and i dont understand this plugin it is Not well layed out or explained.
Whenever i do /is in-game it just teleports me to a different spot in the world i am in and gives me items nothing else no islands created!

i am running:

Hosted Linux Server (RAMShard)
pmmp 3.3.2 (Latest)
Win10 1.7.1
PHP: 7.2

Hope to hear back and Feel free to contact me Here: https://discord.gg/snXHfsN

**Comment by RedCraftGH** [comment]
Hello @AlexPads

I have reopened this issue to inquire with you about your previous observations.

Firstly, do you still think that the plugin is not well laid out and confusing to use? If so, what can I do to fix that? Finally, have you found any bugs or problems with the plugin which need to be fixed?

Thank you,
RedCraftPE

**Comment by AlexPads** [comment]
@RedCraftGH Hello! The plugin is getting better! I no longer have y own server and therefore don't use the plugin 😢 I am Closing this.
