### ISSUE TITLE
Error on /is go

### ISSUE THREAD

**Issue by LeoBdt** [RedCraftGH/RedSkyBlock#22]
[15:22:04] [Server thread/CRITICAL]: ErrorException: "Undefined index: World" (EXCEPTION) in "plugins/RedSkyBlock-master/src/RedCraftPE/RedSkyBlock/Commands/SubCommands/Teleport" at line 46

**Comment by LeoBdt** [comment]
:(

**Comment by isoz** [comment]
Stop spamming emojis and issues dude, it seems like a problem on your end if not then try to use the older version.

**Comment by LeoBdt** [comment]
Sorry. i don't want to use the older version. The problem isn't from me

**Comment by isoz** [comment]
What's wrong with older version? I'm running it just fine on a server with 30+ people... I'm only updating until I've tested it enough to be stable... right now we don't know.

**Comment by ManXmaster** [comment]
The problem is on your end since it seems to be working fine on all other server,maybe you have not set up the world file correctly

**Comment by LeoBdt** [comment]
i need an islands per world limitation wich is in the new version.

I've set up the world file correctly with /is setworld

**Comment by LeoBdt** [comment]
It worked correctly with the older version. but i don't want to use it anymore, i've too many player on my server and the gone too far in world and it makes them shaking, that's why i need new version

**Comment by ManXmaster** [comment]
Okay just be patient,vthe developer of the plugin will reach out to you in about a coupke of hours when he gets the time to.

**Comment by LeoBdt** [comment]
yeah i'd be patient, thanks for your "help" bro

**Comment by LeoBdt** [comment]
Btw, do you use the new version?

**Comment by isoz** [comment]
Did you reset the world? because you need to, this is not backwards compatible.

**Comment by LeoBdt** [comment]
Errrr, i can't use the world i used in previous version???? i can't delete all players islands...

**Comment by ManXmaster** [comment]
Since the new update adds the new feature of island world limit you have to reset the previous world

**Comment by isoz** [comment]
Oh well you have to... you can't make the players happy all the time.

**Comment by LeoBdt** [comment]
Okay i see, that's sad but i've to do it. :(

**Comment by RedCraftGH** [comment]
Unfortunately, I wasn't able to make the newer version backward compatible with the older version, but all versions that I release from now on will be backward compatible. So no more resets will be required.
