### ISSUE TITLE
How do you make a Custom Island?

### ISSUE THREAD

**Issue by DiagonalPRO** [RedCraftGH/RedSkyBlock#25]
I am sorry for the issue but i was wondering what are the steps to maks a custom island? I tried like this: 
1./is pos1
2./is pos2
3./is set
4./is custom on
And it crashes the server! Anyway nice plugin!

**Comment by RedCraftGH** [comment]
After using /is set you do not need to use /is custom on. /is custom <on/off> is only used for disabling and enabling custom islands *after* custom islands have been made. Once you use /is set and make an island the island should be the same as the custom island you set. You can read [this](https://github.com/RedCraftGH/RedSkyBlock/wiki/Creating-Custom-Island-Templates) for a detailed description on how to set up custom islands.
