### ISSUE TITLE
Cobble Gen Bug

### ISSUE THREAD

**Issue by AlexPads** [RedCraftGH/RedSkyBlock#26]
Hello, nice to be contributing another issue to your Plugin!

Cobble gens are not working and when players place lave it sometimes does not flow correctly making the cobble gen not function properly.

I found this bug by having players complain that the gens were not working and then I turned off magiccobblegen and they all stated working again.

**Comment by RedCraftGH** [comment]
@AlexPads This is not a bug caused by the plugin. Pocketmine currently does not have handling for block pending ticks which sometimes causes liquids to get "stuck."
