### ISSUE TITLE
Magic Cobble Gen

### ISSUE THREAD

**Issue by ZandercraftGames** [RedCraftGH/RedSkyBlock#3]
![image](https://user-images.githubusercontent.com/28664144/49466802-f923d980-f7ce-11e8-929e-1e1d16e92698.png)
I Did the following to make the cobble gen, but it wont work. It only spawns cobble. Not anything I put in the config.

**Comment by RedCraftGH** [comment]
@ZandercraftGames I am aware of this issue and am currently working on a fix for it. For now, I believe if you fill in the bottom block where the water is 2 blocks deep it should work.
