### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EduGH7** [RedCraftGH/RedSkyBlock#33]
What is planned for the next update? And when r u going to add the nether islands, I'm hyped for that, and I love this plugin!🤩

**Comment by ZandercraftGames** [comment]
He has not released a date for Nether islands, but I would expect them pretty soon. In the meantime, you can use the custom islands function to add nether and end islands.

**Comment by EduGH7** [comment]
I think that would be cool if he add a function that if you pay with money in game you can upgrade your cobblestone generator or things like that, or "change the biome"
