### ISSUE TITLE
RedCraftGH

### ISSUE THREAD

**Issue by xMercyTheDeveloper** [RedCraftGH/RedSkyBlock#46]
Hey, When I do lava with water, keeps crashing, help
this is the problem from the console:

"Class 'RedCraftPE\RedSkyBlock\Blocks\BlockIds' not found" (EXCEPTION) in "plugins/RedSkyBlock.phar/src/RedCraftPE/RedSkyBlock/Blocks/Lava" at line 96

**Comment by DanuRoYT** [comment]
ummm....hello???
