### ISSUE TITLE
Pls update

### ISSUE THREAD

**Issue by Karanztez** [RedCraftGH/RedSkyBlock#5]
Island top and other

**Comment by RedCraftGH** [comment]
I'll try and get a very, very large update out soon!

**Comment by Karanztez** [comment]
Can you increase the questsUI island?

**Comment by RedCraftGH** [comment]
@Karanztez I'm not sure what you mean. As far as I know, this plugin doesn't have any questsUI.

**Comment by Karanztez** [comment]
Thx
