### ISSUE TITLE
Custom Island Gone on master branch

### ISSUE THREAD

**Issue by Lycol50** [RedCraftGH/RedSkyBlock#61]
using master branch, you cannot create a custom island for the server skyblock, on the poggit release, the feature is there.
 

> You can set the zone for custom islan by doing /is setzone <1/2>, but theres no way to create a custom island

**Comment by RedCraftGH** [comment]
Sure you can. Have you tried using /is updatezone after setting the island zones?

**Comment by Lycol50** [comment]
please provide documentation on how to create islands zones, when using the `master` branch

**Comment by RedCraftGH** [comment]
Do you mean like this documentation here that I provided on how to create island zones when using the master branch?
https://github.com/RedCraftGH/RedSkyBlock/wiki/Setting-up-with-Commands
