### ISSUE TITLE
MultiWorld

### ISSUE THREAD

**Issue by xKurt** [RedCraftGH/RedSkyBlock#65]
Hi,
Let players go and create their islands with different worlds, creating their islands in just one world is extremely laggy.

**Comment by iZeaoGamer** [comment]
> Hi,
> Let players go and create their islands with different worlds, creating their islands in just one world is extremely laggy.

It'll lag the server if you create islands in too many worlds, as worlds take resources.

**Comment by reyyan987** [comment]
Yes it is right

**Comment by xKurt** [comment]
But it’ll also lag in just one world, I’ve tried it before and in every move it’ll shake the screen (since a lot of islands were created). So I tried a skyblock with multiworld and it is a lot better.
Otherwise how we’ll prevent the shake screen?

**Comment by RedCraftGH** [comment]
@xKurt Thanks for your suggestion! However, I do not plan on adding support for this. May I ask, what version of the plugin are you using when this shaking occurs?

**Comment by xKurt** [comment]
RedSkyBlock 3.1.1

It does shake the screen since I think almost thousands of islands were created, so we switched to the Skyblock plugin where it does create MultiWorld and it is actually pretty good.
Also in 3.1.1 is kinda tricky because when you created an island, the custom island that you made will show but mostly not (void). Therefore you kinda need to do it multiple times (creating island) for you to have the custom island, not the void.

I haven’t tried the new RedSkyBlock 5.0.0
Can I ask if these issues are fixed otherwise 5.0.0 is stable?

Plus, I think the screen is shaking because the location of the island is too far for eg. X:2573929 Y:50 Z:2783932. I have tried it on an infinite world and it does really shake the screen if you are too far from X:0 Y:0 Z:0
Therefore I think, shaking screen issue wouldn’t be fixed (might be a pocketmine issue)

Thanks!

**Comment by RedCraftGH** [comment]
@xKurt I sort of assumed you were on 3.1.1 because this problem has surfaced before for that version. Luckily, all of the problems you're having have been fixed in 5.0.0 including the shaking.

**Comment by xKurt** [comment]
Oh okay! Thanks a lot! I’ll try it. 😊

**Comment by xKurt** [comment]
Um, I have checked the plugin and it really does shake still. I have set the Skyblock world and I teleported to 3000000, 50, 3000000.
https://streamable.com/mv0udw

**Comment by RedCraftGH** [comment]
@xKurt Hey! So, regardless of the world which you are in, going 3 million blocks out is going to make your screen shake. However, what's different this time on RedSkyBlock is the way islands are generated. In earlier versions it was possible for islands to get so far out, but in newer versions islands are fit more precisely into the world. Basically, you'd have to have wayyyyyyy more players to even come close to a million blocks out compared to earlier versions where only hundreds of players would make islands a million blocks out.
