### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by llPushkarSinghll** [RedCraftGH/RedSkyBlock#72]
Too many bugs in new version.pls solve it as fast as possible

**Comment by RedCraftGH** [comment]
@llPushkarSinghll Sorry to hear you're having issues with the plugin. However, this is not an effective way of letting me know about your problems. Please create an issue and accurately describe any bugs you've encountered. Also include steps to reproduce these bugs if possible. Lastly, check the console for errors and report any on your issue.
