### ISSUE TITLE
Island Border or New Worlds

### ISSUE THREAD

**Issue by WinterHellMC** [RedCraftGH/RedSkyBlock#80]
So here is my issue,
Imagine someone has island fly permission they can still fly out of their island size limit and go to other islands flying and can destroy them since it's on the same world.
So my request is either add an island border like java edition I don't think it's possible in pmmp but at least make it teleport you back when u go out of your island size limit.
or just make it like GiantQuartz where your island will be generated on a new world instead of the same

**Comment by RedCraftGH** [comment]
@WinterHellMC Thanks for reaching out. Fortunately, precautions have already been set in place considering all of the islands are generated on the same world. If a player were to fly off of their island and go to another, they would not be able to break/place/or use any blocks (unless the player has the permission "skyblock.bypass then they can go anywhere and do anything). Also, in the config.yml there is an option called "Island Boundaries" which, if turned on, does exactly what you're asking for: It adds an invisible border around islands so players cannot leave the islands.
