### ISSUE TITLE
Incompatible network protocol version

### ISSUE THREAD

**Issue by NotSaifA** [RedCraftGH/RedSkyBlock#87]
Pocketmine 3.22.1

Could not load plugin 'RedSkyBlock': Incompatible network protocol version (plugin requires one of: 361, 388, 389, 390, 407, 408, 431, 440)

**Comment by RedCraftGH** [comment]
Thank you for reporting this! I have updated the mcpe-protocol list and added the newest protocol required for the latest stable build of pocketmine.
