### ISSUE TITLE
Player items will still drop after death!

### ISSUE THREAD

**Issue by junxiesky** [RedCraftGH/RedSkyBlock#9]
I'm in config. Keepinventory in the open up the keepinventory, but after death, the player's items will drop

**Comment by RedCraftGH** [comment]
If you want players to keep their items after death set the KeepInventory value to "on"

It should look like this: `KeepInventory: "on"`

**Comment by junxiesky** [comment]
ok，It's my problem,I set it to true，I'm sorry for the trouble
